### ISSUE TITLE
chore: Loggers

### ISSUE THREAD

**Issue by saragee3** [drashland/services#8]
## Summary

What:

`FileLogger` and `ConsoleLogger` from deno-drash should be migrated to this repo.

Why:

This is to prep for the larger Dexter initiative next year. 

## Acceptance Criteria

- [ ] Migrate `FileLogger` and `ConsoleLogger`
- [ ] When merged, fix references to `LoggerService` (https://github.com/search?q=org%3Adrashland+loggerservice&type=code)

**Comment by ebebbington** [comment]
We could probably close this right @saragee3 @crookse ?:) woop woop (a late "woop woop" :P)

**Comment by saragee3** [comment]
WOOP WOOP
